### ISSUE TITLE
Stuck in fetching up with wget when using svptube

### ISSUE THREAD

**Issue by ice051128** [cvzi/mpv-youtube-upnext#11]
Svptube uses youtube-dl to fetch the direct link to videos but this script doesn't work with it for whatever reasons and is stuck in fetching up with wget permanently, why is that?

**Comment by cvzi** [comment]
Sorry I don't use svptube myself. It seems to cost money, so I don't want to buy it just to debug the script.

**Comment by cvzi** [comment]
Can you explain how exactly you use this 'svptube' and where can I download it? 
Like step by step what you do to watch a video, so I can try to recreate the problem.

**Comment by ice051128** [comment]
> Can you explain how exactly you use this 'svptube' and where can I download it? Like step by step what you do to watch a video, so I can try to recreate the problem.

Svptube is part of svp and there's a free trial if you wanna debug this. When I want to watch a video on youtube, I just copy the url and then svptube automatically extracts information on the page with youtube-dl which gives you all the options for video quality and etc. You pick the option you want, say 4k av01, then it passes it to mpv automatically.

**Comment by cvzi** [comment]
I have changed the script to make it work. Unfortunately it cannot preserve the quality settings, because SVP does not make those values available to mpv, so the script can't know which quality was selected.

I needed to put [`yt-dlp.exe`](https://github.com/yt-dlp/yt-dlp) in `C:\Users\USERNAME\AppData\Roaming\mpv\yt-dlp.exe` and then restart computer to make it work. I assume it will also work if `yt-dlp.exe` is in the [PATH](https://www.computerhope.com/issues/ch000549.htm)

**Comment by 2084x** [comment]
Just going to add onto this: The SVP and fetch_on_start commits are sort of conflicting. If fetch_on_start=yes, it causes errors when playing local files because there's now no url checking to return null before the new SVP lines.

I tried implementing the get_url function from [quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu) to do better url detection and it fixed some errors, but idk how to do it properly so I couldn't cover the whole scope of the script.

**Comment by cvzi** [comment]
I think this should fix it

**Comment by ice051128** [comment]
> I think this should fix it

According to the documentation, quality settings that were selected in SVP are not preserved when the next video is load, 
what does it select then? Does it default to highest quality?

**Comment by cvzi** [comment]
I don't know. I just noticed that when I selected a low quality in SVP the next video had a higher quality again. Maybe this also happens because of other settings and scripts that I have installed.
