### ISSUE TITLE
Default font is too big

### ISSUE THREAD

**Issue by vitaly-zdanevich** [cvzi/mpv-youtube-upnext#47]
Hi, my screen is 1366x768, and I think generally most users will be happier to have smaller font out of the box.

**Comment by cvzi** [comment]
Yes it makes sense, I changed it in the config file last year to `{\\fnmonospace\\fs25}`, but didn't change the script. 

Out of curiosity, what font size is good for you? I remember that I tried to find a good default number, and I gave up, because even on my three devices I couldn't find something that looked good on all of them.

**Comment by vitaly-zdanevich** [comment]
Thanks.

Currently I have this:

![image](https://github.com/cvzi/mpv-youtube-upnext/assets/3514015/468d2432-d22c-4150-b89e-78f86d13701d)

Of cource one line for 90% of videos feels like correct UI (like in your README).

23 is good for my 1366x768 laptop:
![2024-jun-20--01-35-23_maim](https://github.com/cvzi/mpv-youtube-upnext/assets/3514015/a3174e52-c850-42ca-b174-ebfeac2ee2a5)
